//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace planovac_2_0.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("planovac_2_0.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Délka nového druhu úkolu musí být od 0 do 20 znaků..
        /// </summary>
        internal static string CHYBA_DRUH {
            get {
                return ResourceManager.GetString("CHYBA_DRUH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Délka názvu musí být od 0 do 40 znaků..
        /// </summary>
        internal static string CHYBA_NAZEV {
            get {
                return ResourceManager.GetString("CHYBA_NAZEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Při načítání nastala chyba.
        /// </summary>
        internal static string CHYBA_PRI_NACITANI {
            get {
                return ResourceManager.GetString("CHYBA_PRI_NACITANI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Při ukládání nastala chyba.
        /// </summary>
        internal static string CHYBA_PRI_UKLADANI {
            get {
                return ResourceManager.GetString("CHYBA_PRI_UKLADANI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba při přidávání události.
        /// </summary>
        internal static string NADPIS_CHYBA_PRIDAVANI_UDALOSTI {
            get {
                return ResourceManager.GetString("NADPIS_CHYBA_PRIDAVANI_UDALOSTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba při přidávání úkolu.
        /// </summary>
        internal static string NADPIS_CHYBA_PRIDAVANI_UKOLU {
            get {
                return ResourceManager.GetString("NADPIS_CHYBA_PRIDAVANI_UKOLU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba při úpravě události.
        /// </summary>
        internal static string NADPIS_CHYBA_UPRAVA_UDALOSTI {
            get {
                return ResourceManager.GetString("NADPIS_CHYBA_UPRAVA_UDALOSTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba při úpravě úkolu..
        /// </summary>
        internal static string NADPIS_CHYBA_UPRAVA_UKOLU {
            get {
                return ResourceManager.GetString("NADPIS_CHYBA_UPRAVA_UKOLU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidání nové události.
        /// </summary>
        internal static string NADPIS_PRIDANI_UDALOST {
            get {
                return ResourceManager.GetString("NADPIS_PRIDANI_UDALOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidání nového úkolu.
        /// </summary>
        internal static string NADPIS_PRIDANI_UKOL {
            get {
                return ResourceManager.GetString("NADPIS_PRIDANI_UKOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úprava události.
        /// </summary>
        internal static string NADPIS_UPRAVA_UDALOST {
            get {
                return ResourceManager.GetString("NADPIS_UPRAVA_UDALOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úprava úkolu.
        /// </summary>
        internal static string NADPIS_UPRAVA_UKOL {
            get {
                return ResourceManager.GetString("NADPIS_UPRAVA_UKOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K události nebyly nalezeny žádné podrobnosti..
        /// </summary>
        internal static string PODROBNOSTI_UDALOST_NO {
            get {
                return ResourceManager.GetString("PODROBNOSTI_UDALOST_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K úkolu nebyly nalezeny žádné podrobnosti..
        /// </summary>
        internal static string PODROBNOSTI_UKOL_NO {
            get {
                return ResourceManager.GetString("PODROBNOSTI_UKOL_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informace o události.
        /// </summary>
        internal static string UDALOST_INFO {
            get {
                return ResourceManager.GetString("UDALOST_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informace o úkolu.
        /// </summary>
        internal static string UKOL_INFO {
            get {
                return ResourceManager.GetString("UKOL_INFO", resourceCulture);
            }
        }
    }
}
